import { db } from './config';
import {
  collection, doc, getDoc, getDocs,
    addDoc, updateDoc, deleteDoc,
      query, where, orderBy, limit,
        serverTimestamp, increment,
          onSnapshot
          } from 'firebase/firestore';

          // ===== USER FUNCTIONS =====
          export const getUser = async (uid) => {
            try {
                const d = await getDoc(doc(db, 'users', uid));
                    return d.exists() ? { id: d.id, ...d.data() }
                          : null;
                            } catch (e) { return null; }
                            };

                            export const updateUser = async (uid, data) => {
                              try {
                                  await updateDoc(doc(db, 'users', uid), data);
                                      return true;
                                        } catch (e) { return false; }
                                        };

                                        export const getTopUsers = async (n = 10) => {
                                          try {
                                              const q = query(collection(db, 'users'),
                                                    orderBy('coins', 'desc'), limit(n));
                                                        const snap = await getDocs(q);
                                                            return snap.docs.map(d =>
                                                                  ({ id: d.id, ...d.data() }));
                                                                    } catch (e) { return []; }
                                                                    };

                                                                    // ===== FOLLOW FUNCTIONS =====
                                                                    export const followUser = async (myUid, theirUid) => {
                                                                      try {
                                                                          await addDoc(collection(db, 'follows'), {
                                                                                followerUid: myUid,
                                                                                      followingUid: theirUid,
                                                                                            createdAt: serverTimestamp()
                                                                                                });
                                                                                                    await updateDoc(doc(db, 'users', myUid),
                                                                                                          { following: increment(1) });
                                                                                                              await updateDoc(doc(db, 'users', theirUid),
                                                                                                                    { followers: increment(1) });
                                                                                                                        return true;
                                                                                                                          } catch (e) { return false; }
                                                                                                                          };

                                                                                                                          export const unfollowUser = async (myUid, theirUid) => {
                                                                                                                            try {
                                                                                                                                const q = query(collection(db, 'follows'),
                                                                                                                                      where('followerUid', '==', myUid),
                                                                                                                                            where('followingUid', '==', theirUid));
                                                                                                                                                const snap = await getDocs(q);
                                                                                                                                                    snap.docs.forEach(d => deleteDoc(d.ref));
                                                                                                                                                        await updateDoc(doc(db, 'users', myUid),
                                                                                                                                                              { following: increment(-1) });
                                                                                                                                                                  await updateDoc(doc(db, 'users', theirUid),
                                                                                                                                                                        { followers: increment(-1) });
                                                                                                                                                                            return true;
                                                                                                                                                                              } catch (e) { return false; }
                                                                                                                                                                              };
                                                                                                                                                                              // ===== BATTLE FUNCTIONS =====
                                                                                                                                                                              export const getBattles = async (type = null) => {
                                                                                                                                                                                try {
                                                                                                                                                                                    let q;
                                                                                                                                                                                        if (type) {
                                                                                                                                                                                              q = query(collection(db, 'battles'),
                                                                                                                                                                                                      where('type', '==', type),
                                                                                                                                                                                                              orderBy('createdAt', 'desc'), limit(20));
                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                        q = query(collection(db, 'battles'),
                                                                                                                                                                                                                                orderBy('createdAt', 'desc'), limit(20));
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                        const snap = await getDocs(q);
                                                                                                                                                                                                                                            return snap.docs.map(d =>
                                                                                                                                                                                                                                                  ({ id: d.id, ...d.data() }));
                                                                                                                                                                                                                                                    } catch (e) { return []; }
                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                    export const createBattle = async (data) => {
                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                          const ref = await addDoc(
                                                                                                                                                                                                                                                                collection(db, 'battles'), {
                                                                                                                                                                                                                                                                      ...data,
                                                                                                                                                                                                                                                                            votesA: 0, votesB: 0,
                                                                                                                                                                                                                                                                                  voters: [],
                                                                                                                                                                                                                                                                                        createdAt: serverTimestamp()
                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                return ref.id;
                                                                                                                                                                                                                                                                                                  } catch (e) { return null; }
                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                  export const voteOnBattle = async (
                                                                                                                                                                                                                                                                                                    battleId, side, uid) => {
                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                          const ref = doc(db, 'battles', battleId);
                                                                                                                                                                                                                                                                                                              const field = side === 'A'
                                                                                                                                                                                                                                                                                                                    ? 'votesA' : 'votesB';
                                                                                                                                                                                                                                                                                                                        await updateDoc(ref, {
                                                                                                                                                                                                                                                                                                                              [field]: increment(1),
                                                                                                                                                                                                                                                                                                                                    voters: [...(await getDoc(ref))
                                                                                                                                                                                                                                                                                                                                            .data().voters, uid]
                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                    return true;
                                                                                                                                                                                                                                                                                                                                                      } catch (e) { return false; }
                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                      // ===== COIN FUNCTIONS =====
                                                                                                                                                                                                                                                                                                                                                      export const addCoins = async (uid, amount) => {
                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                            await updateDoc(doc(db, 'users', uid), {
                                                                                                                                                                                                                                                                                                                                                                  coins: increment(amount)
                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                          return true;
                                                                                                                                                                                                                                                                                                                                                                            } catch (e) { return false; }
                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                            export const claimDailyReward = async (uid) => {
                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                  const ref = doc(db, 'users', uid);
                                                                                                                                                                                                                                                                                                                                                                                      const d = await getDoc(ref);
                                                                                                                                                                                                                                                                                                                                                                                          const today = new Date().toDateString();
                                                                                                                                                                                                                                                                                                                                                                                              if (d.data()?.lastDailyClaim === today)
                                                                                                                                                                                                                                                                                                                                                                                                    return false;
                                                                                                                                                                                                                                                                                                                                                                                                        await updateDoc(ref, {
                                                                                                                                                                                                                                                                                                                                                                                                              coins: increment(2),
                                                                                                                                                                                                                                                                                                                                                                                                                    lastDailyClaim: today
                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                            return true;
                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (e) { return false; }
                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                              // ===== ZONE FUNCTIONS =====
                                                                                                                                                                                                                                                                                                                                                                                                                              export const getZones = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                    const snap = await getDocs(
                                                                                                                                                                                                                                                                                                                                                                                                                                          collection(db, 'zones'));
                                                                                                                                                                                                                                                                                                                                                                                                                                              return snap.docs.map(d =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ({ id: d.id, ...d.data() }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (e) { return []; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                      export const captureZone = async (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        zoneId, uid, username, coins) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              await updateDoc(doc(db, 'zones', zoneId), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ownerUid: uid,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ownerName: username,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                capturedAt: serverTimestamp()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await addCoins(uid, coins);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (e) { return false; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // ===== CHAT FUNCTIONS =====
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export const getDMId = (uid1, uid2) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return [uid1, uid2].sort().join('_');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export const sendMessage = async (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dmId, data) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await addDoc(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              collection(db, 'dms', dmId, 'messages'), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...data,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          createdAt: serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                deleted: false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (e) { return false; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export const listenMessages = (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dmId, callback) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const q = query(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  collection(db, 'dms', dmId, 'messages'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      orderBy('createdAt', 'asc'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return onSnapshot(q, snap => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            callback(snap.docs.map(d =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ({ id: d.id, ...d.data() })));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ===== REFERRAL FUNCTIONS =====
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export const applyReferral = async (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      newUid, referralCode) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const q = query(collection(db, 'users'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  where('referralCode', '==', referralCode));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const snap = await getDocs(q);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (snap.empty) return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const referrerDoc = snap.docs[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const referrerUid = referrerDoc.id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (referrerUid === newUid) return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await addCoins(referrerUid, 25);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await addCoins(newUid, 10);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await updateDoc(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        doc(db, 'users', newUid), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              referredBy: referrerUid
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (e) { return false; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ===== SEARCH FUNCTIONS =====
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export const searchUsers = async (text) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const q = query(collection(db, 'users'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    orderBy('username'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          where('username', '>=', text),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                where('username', '<=', text + '\uf8ff'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      limit(10));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const snap = await getDocs(q);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return snap.docs.map(d =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ({ id: d.id, ...d.data() }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (e) { return []; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // ===== LIVE LISTENERS =====
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export const listenOnlineUsers = (callback) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return onSnapshot(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            collection(db, 'online'), snap => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                callback(snap.size);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export const setOnline = async (uid) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await updateDoc(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              doc(db, 'online', uid), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    uid, lastSeen: serverTimestamp()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await addDoc(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    collection(db, 'online'), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          uid, lastSeen: serverTimestamp()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };