import React, { useState, useEffect } from 'react';
import {
  View, Text, FlatList, TouchableOpacity,
    StyleSheet, StatusBar, RefreshControl
    } from 'react-native';
    import { db } from '../firebase/config';
    import { collection, query, orderBy, limit, getDocs } from 'firebase/firestore';
    import { auth } from '../firebase/config';

    export default function HomeScreen({ navigation }) {
      const [battles, setBattles] = useState([]);
        const [loading, setLoading] = useState(true);
          const [refreshing, setRefreshing] = useState(false);
            const [userData, setUserData] = useState(null);

              useEffect(() => {
                  fetchBattles();
                      fetchUserData();
                        }, []);

                          const fetchUserData = async () => {
                              try {
                                    const { doc, getDoc } = await import('firebase/firestore');
                                          const userDoc = await getDoc(doc(db, 'users', auth.currentUser.uid));
                                                if (userDoc.exists()) setUserData(userDoc.data());
                                                    } catch (e) {}
                                                      };

                                                        const fetchBattles = async () => {
                                                            try {
                                                                  const q = query(collection(db, 'battles'),
                                                                          orderBy('createdAt', 'desc'), limit(20));
                                                                                const snapshot = await getDocs(q);
                                                                                      const list = snapshot.docs.map(d => ({ id: d.id, ...d.data() }));
                                                                                            setBattles(list);
                                                                                                } catch (e) {}
                                                                                                    setLoading(false);
                                                                                                        setRefreshing(false);
                                                                                                          };

                                                                                                            const onRefresh = () => {
                                                                                                                setRefreshing(true);
                                                                                                                    fetchBattles();
                                                                                                                      };

                                                                                                                        const getBattleTypeEmoji = (type) => {
                                                                                                                            if (type === 'vote') return '🗳️';
                                                                                                                                if (type === 'prediction') return '🔮';
                                                                                                                                    if (type === 'roast') return '🔥';
                                                                                                                                        return '⚔️';
                                                                                                                                          };

                                                                                                                                            const renderBattle = ({ item }) => (
                                                                                                                                                <TouchableOpacity
                                                                                                                                                      style={styles.battleCard}
                                                                                                                                                            onPress={() => navigation.navigate('Battle', { battle: item })}>
                                                                                                                                                                  <View style={styles.battleHeader}>
                                                                                                                                                                          <Text style={styles.battleType}>
                                                                                                                                                                                    {getBattleTypeEmoji(item.type)} {item.type?.toUpperCase()} BATTLE
                                                                                                                                                                                            </Text>
                                                                                                                                                                                                    <Text style={styles.battleCoins}>🪙 {item.coins || 10}</Text>
                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                <Text style={styles.battleQuestion}>{item.question}</Text>
                                                                                                                                                                                                                      {item.type === 'vote' && (
                                                                                                                                                                                                                              <View style={styles.optionsRow}>
                                                                                                                                                                                                                                        <View style={styles.optionA}>
                                                                                                                                                                                                                                                    <Text style={styles.optionText}>👊 {item.optionA}</Text>
                                                                                                                                                                                                                                                              </View>
                                                                                                                                                                                                                                                                        <Text style={styles.vsText}>VS</Text>
                                                                                                                                                                                                                                                                                  <View style={styles.optionB}>
                                                                                                                                                                                                                                                                                              <Text style={styles.optionText}>👊 {item.optionB}</Text>
                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                            <View style={styles.battleFooter}>
                                                                                                                                                                                                                                                                                                                                    <Text style={styles.footerText}>👤 {item.createdBy}</Text>
                                                                                                                                                                                                                                                                                                                                            <Text style={styles.footerText}>🗳️ {item.totalVotes || 0} votes</Text>
                                                                                                                                                                                                                                                                                                                                                  </View>
                                                                                                                                                                                                                                                                                                                                                      </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                              <View style={styles.container}>
                                                                                                                                                                                                                                                                                                                                                                    <StatusBar barStyle="light-content" />
                                                                                                                                                                                                                                                                                                                                                                          <View style={styles.header}>
                                                                                                                                                                                                                                                                                                                                                                                  <Text style={styles.headerTitle}>Adda UP 🔥</Text>
                                                                                                                                                                                                                                                                                                                                                                                          <View style={styles.headerRight}>
                                                                                                                                                                                                                                                                                                                                                                                                    {userData && (
                                                                                                                                                                                                                                                                                                                                                                                                                <TouchableOpacity
                                                                                                                                                                                                                                                                                                                                                                                                                              style={styles.coinBadge}
                                                                                                                                                                                                                                                                                                                                                                                                                                            onPress={() => navigation.navigate('Coins')}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Text style={styles.coinText}>🪙 {userData.coins}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <View style={styles.madeInUPBanner}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text style={styles.madeInUPText}>🧡 Made in UP — Apna Adda, Apni Pehchaan</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <View style={styles.center}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Text style={styles.loadingText}>Load ho raha hai... ⏳</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : battles.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <View style={styles.center}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Text style={styles.emptyText}>Abhi koi battle nahi hai!</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.emptySubText}>Pehle battle shuru karo 🔥</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <FlatList
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data={battles}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              renderItem={renderBattle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        keyExtractor={item => item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  contentContainerStyle={styles.list}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            refreshControl={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <RefreshControl refreshing={refreshing} onRefresh={onRefresh}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      tintColor="#ff6b35" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      container: { flex: 1, backgroundColor: '#1a1a2e' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        header: { flexDirection: 'row', justifyContent: 'space-between',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alignItems: 'center', padding: 15, paddingTop: 50,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: '#16213e' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  headerTitle: { fontSize: 24, fontWeight: 'bold', color: '#ff6b35' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    headerRight: { flexDirection: 'row', alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      coinBadge: { backgroundColor: '#ff6b3520', paddingHorizontal: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          paddingVertical: 6, borderRadius: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            coinText: { color: '#ff6b35', fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              madeInUPBanner: { backgroundColor: '#ff6b3515', padding: 8, alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                madeInUPText: { color: '#ff6b35', fontSize: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  list: { padding: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    battleCard: { backgroundColor: '#16213e', borderRadius: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 15, marginBottom: 15, borderWidth: 1, borderColor: '#0f3460' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          battleHeader: { flexDirection: 'row', justifyContent: 'space-between',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                battleType: { color: '#ff6b35', fontWeight: 'bold', fontSize: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  battleCoins: { color: '#ffd700', fontSize: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    battleQuestion: { color: '#fff', fontSize: 16, fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          optionsRow: { flexDirection: 'row', alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              justifyContent: 'space-between', marginBottom: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                optionA: { flex: 1, backgroundColor: '#0f3460', padding: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 10, marginRight: 5 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      optionB: { flex: 1, backgroundColor: '#e94560', padding: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: 10, marginLeft: 5 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            optionText: { color: '#fff', fontSize: 13, textAlign: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              vsText: { color: '#ff6b35', fontWeight: 'bold', marginHorizontal: 5 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                battleFooter: { flexDirection: 'row', justifyContent: 'space-between' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  footerText: { color: '#888', fontSize: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      loadingText: { color: '#888', fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        emptyText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          emptySubText: { color: '#888', fontSize: 14, marginTop: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });