import React, { useState } from 'react';
import {
  View, Text, TextInput, TouchableOpacity,
    StyleSheet, StatusBar, Alert
    } from 'react-native';
    import { Audio } from 'expo-av';
    import { loginUser } from '../firebase/auth';

    export default function LoginScreen({ navigation }) {
      const [email, setEmail] = useState('');
        const [password, setPassword] = useState('');
          const [loading, setLoading] = useState(false);

            const playSound = async (type) => {
                try {
                      const { sound } = await Audio.Sound.createAsync(
                              type === 'success'
                                        ? require('../assets/login_success.mp3')
                                                  : type === 'wrongPassword'
                                                            ? require('../assets/wrong_password.mp3')
                                                                      : require('../assets/wrong_username.mp3')
                                                                            );
                                                                                  await sound.playAsync();
                                                                                      } catch (e) {}
                                                                                        };

                                                                                          const handleLogin = async () => {
                                                                                              if (!email || !password) {
                                                                                                    Alert.alert('Ruko!', 'Email aur password dono daalo!');
                                                                                                          return;
                                                                                                              }
                                                                                                                  setLoading(true);
                                                                                                                      const result = await loginUser(email, password);
                                                                                                                          setLoading(false);
                                                                                                                              if (result.success) {
                                                                                                                                    await playSound('success');
                                                                                                                                        } else {
                                                                                                                                              if (result.error.includes('password')) {
                                                                                                                                                      await playSound('wrongPassword');
                                                                                                                                                            } else {
                                                                                                                                                                    await playSound('wrongUsername');
                                                                                                                                                                          }
                                                                                                                                                                                Alert.alert('Galat!', result.error);
                                                                                                                                                                                    }
                                                                                                                                                                                      };

                                                                                                                                                                                        return (
                                                                                                                                                                                            <View style={styles.container}>
                                                                                                                                                                                                  <StatusBar barStyle="light-content" />
                                                                                                                                                                                                        <View style={styles.topBadge}>
                                                                                                                                                                                                                <Text style={styles.madeInUP}>🧡 Made in UP</Text>
                                                                                                                                                                                                                      </View>
                                                                                                                                                                                                                            <View style={styles.logoContainer}>
                                                                                                                                                                                                                                    <Text style={styles.logoText}>Adda UP</Text>
                                                                                                                                                                                                                                            <Text style={styles.tagline}>UP ka apna adda! 🔥</Text>
                                                                                                                                                                                                                                                  </View>
                                                                                                                                                                                                                                                        <View style={styles.formContainer}>
                                                                                                                                                                                                                                                                <TextInput
                                                                                                                                                                                                                                                                          style={styles.input}
                                                                                                                                                                                                                                                                                    placeholder="Email daalo"
                                                                                                                                                                                                                                                                                              placeholderTextColor="#888"
                                                                                                                                                                                                                                                                                                        value={email}
                                                                                                                                                                                                                                                                                                                  onChangeText={setEmail}
                                                                                                                                                                                                                                                                                                                            keyboardType="email-address"
                                                                                                                                                                                                                                                                                                                                      autoCapitalize="none"
                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                      <TextInput
                                                                                                                                                                                                                                                                                                                                                                style={styles.input}
                                                                                                                                                                                                                                                                                                                                                                          placeholder="Password daalo"
                                                                                                                                                                                                                                                                                                                                                                                    placeholderTextColor="#888"
                                                                                                                                                                                                                                                                                                                                                                                              value={password}
                                                                                                                                                                                                                                                                                                                                                                                                        onChangeText={setPassword}
                                                                                                                                                                                                                                                                                                                                                                                                                  secureTextEntry
                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                  <TouchableOpacity
                                                                                                                                                                                                                                                                                                                                                                                                                                            style={styles.loginBtn}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      onPress={handleLogin}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Text style={styles.loginBtnText}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {loading ? 'Wait karo...' : 'Login Karo 🚀'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <TouchableOpacity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onPress={() => navigation.navigate('Signup')}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.signupText}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Naya account? <Text style={styles.signupLink}>Signup karo!</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                container: { flex: 1, backgroundColor: '#1a1a2e' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  topBadge: { alignItems: 'center', marginTop: 50 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    madeInUP: { color: '#ff6b35', fontSize: 14, fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: '#ff6b3520', paddingHorizontal: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            paddingVertical: 5, borderRadius: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              logoContainer: { alignItems: 'center', marginTop: 40, marginBottom: 50 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logoText: { fontSize: 48, fontWeight: 'bold', color: '#ff6b35' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  tagline: { color: '#888', fontSize: 16, marginTop: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    formContainer: { paddingHorizontal: 30 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      input: { backgroundColor: '#16213e', color: '#fff', padding: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: 12, marginBottom: 15, fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderWidth: 1, borderColor: '#0f3460' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loginBtn: { backgroundColor: '#ff6b35', padding: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 12, alignItems: 'center', marginTop: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      loginBtnText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        signupText: { color: '#888', textAlign: 'center', marginTop: 20, fontSize: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          signupLink: { color: '#ff6b35', fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });