import React, { useState } from 'react';
import {
  View, Text, TextInput, TouchableOpacity,
    StyleSheet, StatusBar, Alert, ScrollView
    } from 'react-native';
    import { registerUser } from '../firebase/auth';

    export default function SignupScreen({ navigation }) {
      const [username, setUsername] = useState('');
        const [email, setEmail] = useState('');
          const [password, setPassword] = useState('');
            const [referralCode, setReferralCode] = useState('');
              const [loading, setLoading] = useState(false);

                const handleSignup = async () => {
                    if (!username || !email || !password) {
                          Alert.alert('Ruko!', 'Sabhi fields bharo!');
                                return;
                                    }
                                        if (password.length < 6) {
                                              Alert.alert('Chhota!', 'Password kam se kam 6 characters ka ho!');
                                                    return;
                                                        }
                                                            setLoading(true);
                                                                const result = await registerUser(email, password, username, referralCode);
                                                                    setLoading(false);
                                                                        if (result.success) {
                                                                              Alert.alert('Welcome!', 'Adda UP mein aapka swagat hai! 🎉');
                                                                                  } else {
                                                                                        Alert.alert('Error!', result.error);
                                                                                            }
                                                                                              };

                                                                                                return (
                                                                                                    <ScrollView style={styles.container}>
                                                                                                          <StatusBar barStyle="light-content" />
                                                                                                                <View style={styles.topBadge}>
                                                                                                                        <Text style={styles.madeInUP}>🧡 Made in UP</Text>
                                                                                                                              </View>
                                                                                                                                    <View style={styles.logoContainer}>
                                                                                                                                            <Text style={styles.logoText}>Adda UP</Text>
                                                                                                                                                    <Text style={styles.tagline}>Nayi shuruat karo! 🚀</Text>
                                                                                                                                                          </View>
                                                                                                                                                                <View style={styles.formContainer}>
                                                                                                                                                                        <TextInput
                                                                                                                                                                                  style={styles.input}
                                                                                                                                                                                            placeholder="Username daalo"
                                                                                                                                                                                                      placeholderTextColor="#888"
                                                                                                                                                                                                                value={username}
                                                                                                                                                                                                                          onChangeText={setUsername}
                                                                                                                                                                                                                                    autoCapitalize="none"
                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                    <TextInput
                                                                                                                                                                                                                                                              style={styles.input}
                                                                                                                                                                                                                                                                        placeholder="Email daalo"
                                                                                                                                                                                                                                                                                  placeholderTextColor="#888"
                                                                                                                                                                                                                                                                                            value={email}
                                                                                                                                                                                                                                                                                                      onChangeText={setEmail}
                                                                                                                                                                                                                                                                                                                keyboardType="email-address"
                                                                                                                                                                                                                                                                                                                          autoCapitalize="none"
                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                          <TextInput
                                                                                                                                                                                                                                                                                                                                                    style={styles.input}
                                                                                                                                                                                                                                                                                                                                                              placeholder="Password daalo (min 6 characters)"
                                                                                                                                                                                                                                                                                                                                                                        placeholderTextColor="#888"
                                                                                                                                                                                                                                                                                                                                                                                  value={password}
                                                                                                                                                                                                                                                                                                                                                                                            onChangeText={setPassword}
                                                                                                                                                                                                                                                                                                                                                                                                      secureTextEntry
                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                      <TextInput
                                                                                                                                                                                                                                                                                                                                                                                                                                style={styles.input}
                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Referral code (optional)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholderTextColor="#888"
                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={referralCode}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChangeText={setReferralCode}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  autoCapitalize="characters"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <TouchableOpacity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={styles.signupBtn}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onPress={handleSignup}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Text style={styles.signupBtnText}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {loading ? 'Wait karo...' : 'Account Banao 🎉'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <TouchableOpacity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onPress={() => navigation.navigate('Login')}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.loginText}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Pehle se account hai?{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text style={styles.loginLink}>Login karo!</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            container: { flex: 1, backgroundColor: '#1a1a2e' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              topBadge: { alignItems: 'center', marginTop: 50 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                madeInUP: { color: '#ff6b35', fontSize: 14, fontWeight: 'bold',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    backgroundColor: '#ff6b3520', paddingHorizontal: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        paddingVertical: 5, borderRadius: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          logoContainer: { alignItems: 'center', marginTop: 40, marginBottom: 50 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logoText: { fontSize: 48, fontWeight: 'bold', color: '#ff6b35' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              tagline: { color: '#888', fontSize: 16, marginTop: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                formContainer: { paddingHorizontal: 30, paddingBottom: 50 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  input: { backgroundColor: '#16213e', color: '#fff', padding: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 12, marginBottom: 15, fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderWidth: 1, borderColor: '#0f3460' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            signupBtn: { backgroundColor: '#ff6b35', padding: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 12, alignItems: 'center', marginTop: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  signupBtnText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    loginText: { color: '#888', textAlign: 'center', marginTop: 20, fontSize: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      loginLink: { color: '#ff6b35', fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });